[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 